### ISSUE TITLE
Remove old repositories

### ISSUE THREAD

**Issue by bartekbrak** [brakdev/Facely#3]
Github has a bit complex set of permissions and entities (organizations, teams, projects, issues, linked porojects), so I want to administer all of that and not burden students with setting this up. 

We started at [Strelau/Facely](https://github.com/Strelau/Facely) and moved to [brakdev/Facely(]https://github.com/brakdev/Facely), the first one is not needed and will confuse us and readers.

Delete `Strelau/Facely`

**Comment by Strelau** [comment]
I deleted old repository  https://github.com/Strelau/Facely

**Comment by bartekbrak** [comment]
now @jasandra delete `https://github.com/jasandra/Facely`.

**Comment by jasandra** [comment]
Delete https://github.com/jasandra/Facely done.

**Comment by bartekbrak** [comment]
Thanks guys!
